apiVersion: v1
kind: ServiceAccount
metadata:
  name: actions-runner-controller
  namespace: arc-systems
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: actions-runner-controller
rules:
- apiGroups: [""]
  resources: ["pods", "secrets", "configmaps", "events"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["actions.summerwind.dev"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: actions-runner-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: actions-runner-controller
subjects:
- kind: ServiceAccount
  name: actions-runner-controller
  namespace: arc-systems
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-runner-controller
  namespace: arc-systems
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actions-runner-controller
  template:
    metadata:
      labels:
        app: actions-runner-controller
    spec:
      serviceAccountName: actions-runner-controller
      containers:
      - name: manager
        image: summerwind/actions-runner-controller:v0.27.6
        env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: controller-manager
              key: github_token
        ports:
        - containerPort: 9443
          name: webhook
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi