apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: tsviz-runners
  namespace: arc-systems
spec:
  replicas: 3
  template:
    spec:
      organization: tsviz
      env:
        - name: RUNNER_FEATURE_FLAG_EPHEMERAL
          value: "true"
      resources:
        limits:
          cpu: "2.0"
          memory: "1Gi"
        requests:
          cpu: "100m"
          memory: "64Mi"
      # Use the GitHub token secret we created
      envFrom:
        - secretRef:
            name: controller-manager
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: tsviz-runners-autoscaler
  namespace: arc-systems
spec:
  scaleTargetRef:
    name: tsviz-runners
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - "arc-config-mcp"